# Generated by Django 4.1.3 on 2023-02-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.intrest'),
        ),
    ]
